import Head from 'next/head'; 
import { BsFillMoonStarsFill } from 'react-icons/bs'
import { 
  AiFillTwitterCircle, 
  AiFillLinkedin, 
  AiFillGithub 
} from 'react-icons/ai'
import Image from 'next/image'
import me from '../public/me.jpg'
import design from '../public/design.png'
import code from '../public/code.png'
import consulting from '../public/consulting.png'
import web1 from '../public/web1.png';
import web2 from '../public/web2.png';
import web3 from '../public/web3.png';
import web4 from '../public/web4.png';
import web5 from '../public/web5.png';
import web6 from '../public/web6.png';
import { useState } from 'react'; 

export default function Home() {

  const [darkMode, setDarkMode] = useState(false); 

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Adarsh</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.2.19/tailwind.min.css" />
      </Head>
      <main className='bg-white w-screen'>
        {/* Section-1 */}
        <section className="min-h-screen">
          <nav className="px-10 md:px-20 lg:px-40 py-6 mb-12 flex justify-between shadow-lg">
            <ul class="flex items-center gap-12">
              <li class="font-burtons text-lg mt-2">AdarsH</li>
              <li>About</li>
              <li>Projects</li>
              <li>Tech Stack</li>
            </ul>
            <ul class="flex items-center">
              <li>
                <BsFillMoonStarsFill className='cursor-pointer text-2xl'/>
              </li>
            </ul>
          </nav>
          {/* front page */}
          <div 
            className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-52 h-52 overflow-hidden md:h-64 md:w-64'
          >
            <Image src={me} layout="fill" objectFit='cover'/>
          </div>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>Adarsh Rawat</h2>
            <h3 className='text-2xl py-2 md:text-3xl'>Developer and Open Source Enthusiast.</h3>
            <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto'>
              Learning new Techs in Web D space and Contributing in open Source. 
            </p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillGithub />
          </div>
        </section>
        {/* Section-2 */}
        <section class='px-10 md:px-20 lg:px-40'>
          <div>
            <h3 className='text-3xl py-1'>Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800">
              Since the beginning of my journey as a freelance designer and
              developer, I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <div className='lg:flex gap-10'>
            {/* Card-1 */}
            <div className='text-center shadow-lg p-10 rounded-xl my-10 flex-1'>
              <Image src={design} width={100} height={100} className='mx-auto'/>
              <h3 className='text-lg font-medium pt-8 pb-2'>
                Beautiful Designs
              </h3>
              <p className='py-2'>
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className='py-4 text-teal-600'>Tech Stack I use</h4>
              <p className='text-gray-800 py-1'>Next</p>
              <p className='text-gray-800 py-1'>Tailwind</p>
              <p className='text-gray-800 py-1'>Flask</p>
            </div>
            {/* Card-2 */}
            <div className='text-center shadow-lg p-10 rounded-xl my-10 flex-1'>
              <Image src={code} width={100} height={100} className='mx-auto'/>
              <h3 className='text-lg font-medium pt-8 pb-2'>
                Beautiful Designs
              </h3>
              <p className='py-2'>
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className='py-4 text-teal-600'>Tech Stack I use</h4>
              <p className='text-gray-800 py-1'>Next</p>
              <p className='text-gray-800 py-1'>Tailwind</p>
              <p className='text-gray-800 py-1'>Flask</p>
            </div>
            {/* Card-3 */}
            <div className='text-center shadow-lg p-10 rounded-xl my-10 flex-1'>
              <Image src={consulting} width={100} height={100} className='mx-auto'/>
              <h3 className='text-lg font-medium pt-8 pb-2'>
                Beautiful Designs
              </h3>
              <p className='py-2'>
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className='py-4 text-teal-600'>Tech Stack I use</h4>
              <p className='text-gray-800 py-1'>Next</p>
              <p className='text-gray-800 py-1'>Tailwind</p>
              <p className='text-gray-800 py-1'>Flask</p>
            </div>
          </div>
        </section>
        {/* Section-3 */}
        <section className='px-10 md:px-20 lg:px-40'>
          <div>
            <h3 className='text-3xl py-1'>Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800">
              Since the beginning of my journey as a freelance designer and
              developer, I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/3 flex-1'>
              <Image src={web1} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web2} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web3} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web4} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web5} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web6} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
            </div>
          </div>
        </section>
      </main>
    </div>     
  )
}
